### ISSUE TITLE
Prompt for twitter pin waits indefinitely

### ISSUE THREAD

**Issue by tomdickharryeth** [zer0-os/zChain#41]
When calling meow.enableTwitter(true), the prompt prints the pin I enter but does not proceed

After some experimentation it seems to be caused by the prompt-sync call

https://github.com/zer0-os/zChain/blob/66beff28b5aa5286f91f18676e2aa49a6bb5e9bb/apps/meow/src/meow.ts#L320

I haven't found the reason yet but it seems to have been reported by others, eg
https://stackoverflow.com/questions/54649465/how-to-do-try-catch-and-finally-statements-in-typescript

I will keep trying to figure it out but just pinging you guys for awareness

**Comment by ratik21** [comment]
Thanks for creating the issue! Yes, the issue is somewhere asking for a prompt within a REPL. Looking into it.

**Comment by ratik21** [comment]
@tomdickharryeth could you please test now?

**Comment by tomdickharryeth** [comment]
It works! Thanks for the fast turnaround much appreciated!

https://twitter.com/tomdickharryeth/status/1522891895898259456
