### ISSUE TITLE
Add MacOS setup steps to readme

### ISSUE THREAD

**Issue by tomdickharryeth** [zer0-os/zChain#48]
Had a few users asking about this so might be nice to add to readme. Here are the steps from dilden

Make sure you have XCode and Homebrew (https://mac.install.guide/homebrew/2.html)
Make sure you have the latest version of node, I have: v16.15.0 
If you update, close and restart terminal. 

node -v

brew install node

brew install git

sudo npm install -g yarn

git clone https://github.com/zer0-os/zChain.git

sh install.sh

cd zChain

cd packages/meow-cli

sudo npm link --force

cd ../..

meow sandbox

**Comment by ratik21** [comment]
Thanks @tomdickharryeth i have added steps for mac installation in README. Few points:
+ you shouldn't use `brew` for nodejs installation on macs. Use `nvm`
+ avoing using `sudo` npm and reinstall node with non-sudo priveleges.
