### ISSUE TITLE
Doesnt build on M1 / ARM

### ISSUE THREAD

**Issue by lommaj** [zer0-os/zChain#67]
I cant get it to build on M1 mac due to what looks like a x86 dependency for electron.

I will dig in a little and try to get a build.

Didnt work with a rosetta 2 terminal.

**Comment by ratik21** [comment]
@lommaj right, it's an issue with the `wrtc` module (and maybe more). I personally use linux, so wasn't able to test the installation thoroughly on m1 macs. I am adding one method in user docs which worked on an m1 mac mini (by switching the arch). Hope that works. I didn't test with a rosetta 2 terminal. 

Any help is welcome and appreciated. Thanks :)

**Comment by ratik21** [comment]
@lommaj it should work now
